### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by kabirshivanikumar** [kshivani5/kingaisgood#1]
Hi,

I f you're facing a problem creating a Pull Request, I think it's because @kshivani5 does not have anything to compare.

Best,
Kabir S (Mr.)
I'm rechable on e-mail
kshivaniandkyna@gmail.com .

**Comment by kshivani5** [comment]
> Hi,
> 
> I f you're facing a problem creating a Pull Request, I think it's because @kshivani5 does not have anything to compare.
> 
> Best,
> Kabir S (Mr.)
> I'm rechable on e-mail
> [kshivaniandkyna@gmail.com](mailto:kshivaniandkyna@gmail.com) .

Oh...Sry...

**Comment by kshivani5** [comment]
> Hi,
> 
> I f you're facing a problem creating a Pull Request, I think it's because @kshivani5 does not have anything to compare.
> 
> Best,
> Kabir S (Mr.)
> I'm rechable on e-mail
> [kshivaniandkyna@gmail.com](mailto:kshivaniandkyna@gmail.com) .

Ok...Sry...

**Comment by kshivani5** [comment]
> Hi,
> 
> I f you're facing a problem creating a Pull Request, I think it's because @kshivani5 does not have anything to compare.
> 
> Best,
> Kabir S (Mr.)
> I'm rechable on e-mail
> [kshivaniandkyna@gmail.com](mailto:kshivaniandkyna@gmail.com) .

Dear, @kabirshivanikumar 

But I can can create a pull request...
